---
title: Venkat Ganesan | Developer & Wantrepreneur
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: vgkrish619@gmail.com
description: 'Blogs, Tutorials and attempts at projects on the web and mobile technologies  by
  Venkat Ganesan.

'
baseurl: ''
url: ''
twitter_username: vgkrish
github_username: vgvenkat
disqus:
  shortname: venganesan
google_analytics: 
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
